- tests/OneRepo.py
- tests/git_api.py
- tests/md_changelog.py
Buggy, but working version of script that generates markdown.
> Buggy, but working version of script that generates markdown.

- tests/MainPage.py
Fixed bug that duplicates some of the commits in OneRepo.py . Add MainPage.py script that generates a "main page" for our md pages.
> Fix buggs in code. Add MainPage.py

- client.py
- repositories/github_repositories.md
- Added Tooltool to the list of git repositories
- Improved documentation in hg_timestamps_handler() function
- Defined get_hg_changes()
- Corrected datetime format
- Corrected documentation in filter_commit_data()
> Added tooltool to git repos, improved docs, defined get_hg_changes & hg_timestamps_handler()

- client.py
This commit refers to issue #32.
> Add function to generate md table

- client.py
Those changes refer to issue #43
> Update client.py to fix issue #43

- client.py
- repositories.json
* add changes from PR #42 to the last FF-CI version
* modify client.py and repositories.json
> Fix PR #42

- client.py
Those changes refer to issue #47
> Clear buggy indent + add link to commit

- client.py
- repositories.json
- repositories/github_repositories.md
- repositories/mercurial_repositories.md
Update the repositories.json file. Add the correct name, team and url for each repository.
Add the changes we need from PR #53
> This PR fix the issue #50

- repositories.json
Re-added the config lines into repositories.json that have been removed in PR #102
> re-added the version-path config inside repositories.json

- client.py
Rearrange functions in client.py in order, for a better followup of the logic. Previously , it was hard to follow the logic as you had to jump from function to function all over the .py file.
> Rearrange functions in client.py

- client.py
We had unconverted data. Fixed the problem by adding format for the milliseconds.
> added formating for miliseconds as it was giving a value error otherwise

- client.py
- fic_modules/configuration.py
This commits refers to #154 and marks the start for DevMode Milestone
> Add flag configuration and configuration.py file

- client.py
Issue #151 
This PR decomposes filter_git_commit_data in 4 smaller functions.
* filter_git_no_tag - filters the commits from the repositories with no release tags
* filter_git_commit_keyword - filters the commits according to a specific keyword in the commit message
* filter_git_tag_bp - filters the commits from the build-puppet and scriptworker repositories
* filter_git_tag - filters the commits from the repositories with release tags
I'll mark this PR as [WIP] but it can be merged.
>     Issue #151 - Decomposes filter_git_commit_data in 4 smaller functions.

- client.py
- main_md_table.md
Fix #175 . A typo was creating this bug.
> Fix #175 (Hg commit link generation bug)

- client.py
- git_files/balrogscript.md
-added the changes implemented by @mutterroland  in PR #181 
-added the return lines in limit_checker function. The function returns True as long as the limit request is not reached
> Improve pylint rate by solving issues ( fixed the conflicts from PR #181)

- auto-push.py
- client.py
- the logic is implemented in the auto-push-py file and it use the subprocess module in python
- a crontask is set on our station to run the script every hour. 
- the new changes from git_files, hg_files and main_md_table will be pushed on the 'auto-generated-files' branch
Issue #121 and #153
> Implemented an automatic method to run the script and push data to Git

- auto-push.py
- client.py
This commit contains the changes implemented by @mutterroland with the exception of the data update, to avoid conflicts.
> Implement changes from PR 213

- auto-push.py
This PR will fix #215 
**When merged, please delete the branch**
> Issue 215 - Add changelog.json to auto-push.py

- README.md
- client.py
As per our discussion on skype:
- Change `--hg` to `--mercurial`
- Change `--multiple` to `--manual`
This PR will close issue #210
> Issue 210 - Change --hg to --mercurial and --multiple to --manual

- client.py
Fixed issue #225 by adding a default case for the cli arguments.
> Fixed issue 225 by adding a default case for the arguments

- client.py
Moved click import after logging and datetime imports.
> Fixed import order by moving click in the right place

- client.py
Created separated function for each run type and removed the described in issue #227
> Moved code to functions, fix for issue #227

- client.py
Renamed all occurrences for `all` to `complete`
> Renamed 'all' to 'complete', issue #228

- client.py
> Issue 239: Fix problems with click arg rename

- client.py
- fic_modules/configuration.py
Re-implemented `-d` argument.
- Removed `GENERATE_FOR_X_DAYS` from `fic_modules/configuration.py`
- Added default value for -d (default=1)
- Replaced `GENERATE_FOR_X_DAYS` with `days` in every function where `GENERATE_FOR_X_DAYS` was used as a parameter.
> Issue 221: Reimplemented -d argument

- README.md
> Issue 241: Update README.md

- fic_modules/helper_functions.py
This PR replaces `print` with `LOGGER.info` in `limit_checker()`
-Remove `sys` import as it isn't used anymore in `fic_modules/helper_functions.py`
> Issue 235: Replace print with LOGGER in limit_checker()

- fic_modules/hg.py
> Issue 191: Only use requests to grab url data

- fic_modules/helper_functions.py
This PR removes the entry log for **"Link generated for Bug"** and updates the doc string for the function.
This will close issue #257
> Fix issue with PR252

- auto-push.py
> Improve auto-push.py 

- client.py
- fic_modules/git.py
- fic_modules/helper_functions.py
This PR will close issue #205 and issue #245 
- Update DocStrings where needed.
- Removed un-needed explanations, such as "This is a helper function", since we now have a home for them.
- Fixed a bunch of typos.
> Issue 205/245 - Update DocStrings.

- client.py
This PR is for Issue #238:
Added 'keyboardInterruptHandler' function that catch the KeyboardInterrupt Signal and clean the staging environment.
> Issue 238 - Handle script interruptions in the middle of action

- client.py
> [Issue 290] Change default changelog.md generation to 3 days

- auto-push.py
> [Issue-292] Make auto-push swap back to master when everything is finished

- fic_modules/markdown_modules.py
Modified the else into an if that checks for the proper values.
> Fix for issue #347

- client.py
> Issue350: Print when running script with -m flag is buggy

- fic_modules/markdown_modules.py
This PR will fix Issue #356 :
- edited LOGGER.info by adding the name of the repository
> Issue 356: Add a more specific log to 'generate_main_md_table' function

- client.py
* running the script using it, will update all the files and push on github.
> Issue 367 - Added a new parameter: -u, --update

- fic_modules/helper_functions.py
Implemented two new helper functions in `./fic_modules/helper_functions.py` that runs in 2 stages:
1) **file_size(file_path)**: Will take a file path and send it to `convert_bytes()`. Once it receives a return, it will check if the file size it bigger than 999kb. If it is, it will `return True` if it's not, it will return False, file_size
```python
def file_size(file_path):
"""
Implemented in: issue-391
This helper function will return if a file is over 1000kb or not.
If size > 1000: Will return True
If size < 1000: Will return False, size
:param file_path: path for the file you want to check it's size.
:return:
"""
size = None
if os.path.isfile(file_path):
file_info = os.stat(file_path)
size = convert_bytes(file_info.st_size)
if size[0] < 1000 and size[1] == "kb":
return False, …
```
> [Issue-391] Implement filesize checker.

- fic_modules/git.py
- fic_modules/hg.py
- fic_modules/markdown_modules.py
This PR will fix the Issue #396 : 
- replace the absolute path to the .json and .md files with the relative path.
> Issue #396 - relative path issue

- README.md
- modules/FIC_MainMenu.py
- modules/FIC_Mercurial.py
This PR implements the login flag logic and slightly changes the mercurial class.
> Implement MainMenu logic and Small HG updates.

- modules/FIC_DataVault.py
- modules/FIC_MainMenu.py
- modules/FIC_Mercurial.py
This PR changes/add the following:
- Add ```self.hg_commits_list``` to DataVault. This variable will store list of commits for every changeset that is pushed
- Improves to MainMenu.py to allow usage of either arguments either the possibility to select actions from menu
- Refactor the logic in FIC_Mercurial.py to only have an entry point : ```def start(self):```
> Add improvements to MainMenu and Mercurial

- modules/FIC_MainMenu.py
This will fix some weird edge-case logic issues, typos, and implements case 7 menu logic.
> Fix various issues with fic_mainmenu.py

- README.md
- modules/FIC_FileHandler.py
- modules/config.py
- Finish all base functionality (such as: save, load, file size, rename files, etc)
- Implement all the new functionality explained in Issue #420 
I have implemented a bunch of `public methods` and everything we do now expects a `directory and a filename`.
First off, I have implemented a "local" `-dev` argument check. **This is not added as a global argument! Meaning it's not added to FIC_Mainmenu.py logic**.
What do this do? This flag will be used by `FICFileHandler()` to know how to return paths. Usually when we work in a class, we always **had** to hardcode directories, paths, etc. Well not anymore. When you work on `FICDataVault()` as an example, simply add to that file (in PyCharm) the -dev argument, and whenever you work with `FICFileHander()` in `FICDataVault()` paths will be …
> Issue 420 - Extra FileHandler Functionality

- README.md
- modules/FIC_Github.py
- modules/config.py
This PR will fix Issue #411 
Update FIC_Github.py to check the limit requests and change the token.
--------------------------------------------------------------------------
- limit_checker() - returns the number of remaining requests
- switch_token() - switch the token
- add get_token(self) - method that returns the next token from the modules.config.GIT_TOKEN list
Change GIT_TOKEN type as a list that contain the OS.ENV available tokens
-----------------------------------------------------------------------------
- GIT_TOKEN = ["GIT_TOKEN", "GIT_TOKEN_1", "GIT_TOKEN_2"]
> Issue 411 - use multiple tokens

- README.md
- client.py
- modules/FIC_Exceptions.py
- modules/FIC_Github.py
- added 'def revert_modified_files(self):' to checkout the changes on CHANGELOG_JSON_PATH, CHANGELOG_MD_PATH, CHANGELOG_REPO_PATH
- added  'def signal_handler(self, signal, frame):'
> Issue #407 - keyboardInterruptHandler

- modules/FIC_FileHandler.py
This PR will covers points explained in #429
> Issue 429: FileHandler optimizations.

- modules/FIC_Mercurial.py
> Issue436: Remove hardcoded parts from FIC_Mercurial.py

- README.md
- client.py
- fic_modules/FICExceptions.py
- fic_modules/git.py
- fic_modules/markdown_modules.py
This PR should solve issues mentioned in #410, #406 and #405
> Address issue 410, 406 and 405

- README.md
- modules/FIC_Exceptions.py
- added a method to handle github server errors
- added each server error as an exit code into README.md
> handle server errors

- modules/FIC_Utilities.py
Documentation available in issue #446
> Issue 446: Return time utility

- modules/FIC_Github.py
- modules/FIC_Mercurial.py
> Issue450: Add return into FIC_Github.py methods

- modules/FIC_Mercurial.py
This PR addresses the construction of the data that will be written into json files. 
**MENTION**
**The following code:**
```Python
def _construct_json_dict(self):
self.hg_commits_list = {}
self.final_dict = {}
for push in self.changesets_json.get("pushes"):
unformated_date = self.changesets_json.get("pushes").get(push).get("date")
pusher = self.changesets_json.get("pushes").get(push).get("user")
date = self._generate_changeset_date(unformated_date)
self.final_dict.update({push: {"pusher": pusher,
"date_of_push": date,
"changeset_commits": {}}})
for commit in range(len(self.changesets_json.get("pushes").get(push).get("changesets"))):
node = self.changesets_json.get("pushes").get(push).get("changesets")[commit]["node"]
commit_author = …
```
> Issue449 Construct the data to be written into json files(HG PART)

- README.md
- client.py
- modules/FIC_Core.py
- modules/FIC_MainMenu.py
- modules/FIC_Mercurial.py
Worked on run_fic() method and made the script run from client.py without --dev
> Issue 444 - Worked on run_fic() method and made the script run from client.py without --dev

- modules/FIC_Mercurial.py
Imported `HG_CHANGESETS_TO_SHOW` from config.py
Replaced hardcoded value with HG_CHANGESETS_TO_SHOW
> Replaced hardcoded value and imported hg_changesets_to_show from config

- modules/FIC_Core.py
This PR will:
-  add the logic to auto generate the changelog.json, changelog.md and the MD files into FICCore class
-  implement the logging system in FIC_Core.py
> Issue 414 - Make Markdown suport as a plugin

- modules/FIC_Github.py
- modules/FIC_Mercurial.py
This Pr wil fix the Issue #472 
I've replaced the list of files_changed with the number of files_changed to reduce the size of .json files.
> [Issue 473] - Reduce the size of files_changed

- modules/FIC_Core.py
- modules/FIC_Github.py
- add LOGGING 
- add literals f-string text formatting
- clean the code
> Adds improvements in FICCore and FICGithub classes

- README.md
- modules/FIC_Core.py
- modules/FIC_Exceptions.py
- modules/FIC_FileHandler.py
- modules/FIC_Github.py
- modules/FIC_Logger.py
- modules/FIC_MainMenu.py
- modules/FIC_Mercurial.py
- plugins/FIC_Markdown.py
FIC_Github.py docstrings - https://github.com/mozilla-releng/firefox-infra-changelog/commit/9b8c1a5b94d13076c362030e6e9c48ff170c0fe6
FIC_Markdown.py docstrings - https://github.com/mozilla-releng/firefox-infra-changelog/commit/c59dfafd23b777b89115dc89aa84323a75c87d28
FIC_Mercurial.py docstrings - https://github.com/mozilla-releng/firefox-infra-changelog/commit/7ae9641b4617b366c6afbbcff073f03f70899ccd
FIC_Logger.py docstrings - https://github.com/mozilla-releng/firefox-infra-changelog/commit/d13b5df4736707f580cb821558e4243e57464db3
FIC_Exceptions.py docstrings - https://github.com/mozilla-releng/firefox-infra-changelog/commit/59cf4f7659d5de2598f138eaf0beacd18d0596ed
FIC_Core.py  docstrings - https://github.com/mozilla-releng/firefox-infra-changelog/commit/d6bb1b1f3becc2d7612059924ae0172cc05 …
> Issue 481 - Document all of the modules/functions and update README.md

- README.md
- client.py
- modules/FIC_Core.py
- modules/FIC_Exceptions.py
- modules/FIC_FileHandler.py
- modules/FIC_Github.py
- modules/FIC_Logger.py
- modules/FIC_MainMenu.py
- modules/FIC_Mercurial.py
- plugins/FIC_Markdown.py
Please merge this PR after PR #486 
Changed the code in client.py to catch the keyboard interruption signal and GitHub error codes.
> Fix the exception capture system from client.py

- modules/FIC_FileHandler.py
- modules/FIC_Github.py
- modules/FIC_Mercurial.py
- plugins/FIC_Markdown.py
> Issue 481 - added docstrings for the remaining methods

- docs/client.html
- docs/data/index.html
- docs/index.html
- docs/modules/FIC_Core.html
- docs/modules/FIC_DataVault.html
- docs/modules/FIC_Exceptions.html
- docs/modules/FIC_FileHandler.html
- docs/modules/FIC_Github.html
- docs/modules/FIC_Logger.html
- docs/modules/FIC_MainMenu.html
- docs/modules/FIC_Mercurial.html
- docs/modules/FIC_Utilities.html
- docs/modules/config.html
- docs/modules/index.html
- docs/plugins/FIC_Markdown.html
- docs/plugins/index.html
- docs/tests/index.html
FIC Documenatation: https://raduiman.github.io/Time/
> Add the pdoc documentation. html format
