client.py

This commit refactors client.py in order to have the same results ,as previously , but working with github objects. It generates all md and json files and will store them in /git_files. Also , as it is right now, it only store commits that were made last week via **lastWeek = datetime.now() - timedelta(days=7)**(line 9) and **git.get_repo(repository_path).get_commits(since=lastWeek)** (line 75) . If there aren't any commits in the last week , the script will print: **Json for "repo name" is empty! Skipping!**.

Refactor client.py

---

client.py
git_files/taskcluster-auth.json
git_files/taskcluster-auth.md
git_files/taskcluster-queue.json
git_files/taskcluster-queue.md
repositories.json

Added a parameter for create_files_for_hg and create_files_for_git functions because:
- the repositories variable wasn't referenced anymore in the main function 
- someone looking at the code for the first time wouldn't understand how and where this var was used 
- this way it is clearer and easier to understand the flow of the logic. 
- It also allows us to call the 2 aforementioned def's on any json file that has a repo list
Added taskcluster-auth and taskcluster-queue to the git repo list in repositories.json
The script successfully generates the json and MD files for these 2 repos.

added taskcluster repos

---

client.py
repositories.json

- changed filter_git_commit_data to only get commits based on how each repo is configured
- added new functions: get_commit_details & compare files
- made slight modification to the function create_files_for_git:
- it now stores the folders we care about in a repo
- filter_git_commit_data now accepts different arguments
This is just a base version, code polishing is needed.

updated repo configs and re-wrote the logic for how we get commits

---

client.py

This PR will:
- Fix the issue that returns the last deployed commit for each commit that was not deployed. Issue #161
-- this change makes the script to send the list with all the new deployed commits, not with the commits one by one

fix for Issue #161

---

client.py
fic_modules/configuration.py

This is an extension to @bccrisan 's work in #167
Basically it changes the hardcoded days the main markdown table should generate (default 1 day) and implements --d
Just a small change overall.

Add --d flag extension for PR167

---

README.md
client.py
fic_modules/configuration.py
fic_modules/helper_functions.py
fic_modules/hg.py
fic_modules/markdown_modules.py
repositories.json

Modified the following:
* Solved bugs in HG generation process . It used to bring blank changesets. (Changesets that do not contain files we care about when there weren't any .json files generated)
* Update readme.md
* Update configuration.py
* Modified HG generation process
* Update @click part in client.py
* In case we'll have to delete .json files (hard reset), the script will successfully generate new ones
* Add NUMBER_OF_CHANGESETS in configuration.py. This variable is used only when there aren't any hg json files generated. Basically, by modifying this variable , script will generate json/md files for the last number of changesets
* WORKING_DIR is used to step back a folder from /fic_modules to /firefox-infra-changelog. Used because git.py and hg.py are in fic_modules/.
* You might …

Solve HG generation bug, update click

---

fic_modules/git.py
fic_modules/helper_functions.py
repositories.json

- Added script repos as standalone keys in repositories.json
- Removed the logic that was filtering script repos within filter_git_tag_bp()
- Slightly reworked filter_git_tag() to work for mozapkpublisher and the script repos
- This PR closes #208

Reconfigured scriptworker repositories

---

client.py

This PR handles solves the problem of unknown arguments.
However, this needs manual intervention in `valid_args` whenever we implement a new argument.
Had a look if this can be translated into a `try except` but it seems like `click` doesn't let us handle such exceptions.

Issue 236: Handle unknown arguments

---

fic_modules/hg.py
fic_modules/markdown_modules.py

This PR will close Issue #219 
Changed the logic to iterate trough the Json data starting from the end of the dict. (from the newest commit to the oldest commit). 
This PR will fix the order of the HG commits in all MD files:
- [changelog.md](https://github.com/mozilla-releng/firefox-infra-changelog/blob/master/changelog.md)
- [hg_files/[repo_name].md](https://github.com/mozilla-releng/firefox-infra-changelog/tree/master/hg_files)

Issue 219: Fix the Mercurial logic to show commits in the markdown table from the newest to oldest

---

fic_modules/helper_functions.py
fic_modules/hg.py
fic_modules/markdown_modules.py

This PR will close Issue #166 
The function added in this PR will return the commit message with all bug numbers replaced with bugzilla links. 
With this PR the functions that generate the MD tables will use this new function to add the links in the commit messages. 
e.g [Bug 1529210 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1529210) Add new Raptor tests in tp6m-5 r=davehunt

Issue 166: Generate and add Bugzilla links to the bug numbers in markdown files.

---

client.py
fic_modules/git.py
fic_modules/helper_functions.py
fic_modules/hg.py

With these changes the main json, containing all the data from both hg and git files, will only be written once.
This fixed issue #222 
- create_ files_for_git andcreate_ files_for_hg functions now return a dictionary called "complete_data"
- in the variable "complete_data" we store all the git or hg data that needs to be written to changelog.json

Changelog.json is no longer re-written repeatedly

---

README.md
fic_modules/configuration.py
fic_modules/helper_functions.py

PR will fix issue #262 
- OS Environment Variable, called `LoggerLevel`. If variable not offered, fallback to default `logger.INFO`.
- Will print **Invalid Bug number** logs if configuration is set to `logging.WARNING`
- Update `README.md` to include the new logging abilities.

[Issue 262] Implement Logger Level based on Environment variable.

---

fic_modules/git.py
repositories.json

This PR fixes and closes issue #319 : 
- deleted _**filter_git_scriptworkers()**_ as it wasn't used/required anymore
- deleted **new_version_commit_date** and **last_modified variables** since we are no longer using the date & time to determine whether we should save a commit, but rather the commit message

Issue 319 - Saving only the version bumping commit

---

fic_modules/helper_functions.py

This PR will fix Issue #381 
- changed the if condition to catch any occurrence of the string "bug"
```Python                
if "bug" in (commit_text[element].lower()) and element < len(commit_text) - 1:
```
- changed the expression that convert into integer. This will catch only the number (decimal character) from a string.
```Python     
- bug_number = int(bug_number)
+ bug_number = int(''.join(list(filter(str.isdigit, bug_number))))

Issue #381 - Automated Bug "linker" not working on the following - (bug number)

---

plugins/FIC_Markdown.py

This PR contains the following changes: 
- Added `generate_link_for_bugs` static method
- storing the returned result in `self.linked_commit_msg`
- added `str()` conversion to `self.commit_number` and `self.commit_date`

Convert bug numbers into links

---

client.py
update-files.py

- replace the old arguments from client.py documentation block and from valid_args[]
- change the argument in update-files.py:  -a (--all) instead of -c (--complete)
Issue #406

Issue 406 - replace the old arguments from client.py and update-files.py

---

modules/FIC_DataVault.py
modules/FIC_Exceptions.py
modules/FIC_FileHandler.py
modules/FIC_Github.py
repositories.json

This PR will:
-----
- Finished all base functionality explained in Issue #438 -> filter the commits depending of repository type, repository version, repository files that affect CI and keywords.
Public methods:
======
FICGithub().start():                  https://github.com/mozilla-releng/firefox-infra-changelog/pull/448/commits/bf48b7609f0baff69110c2a2891c096b2d2eba6e
----
- I have implemented start() public method, the main method to call after the attribute repo_name is initialized in FICDataVault. The method will return a dictionary containing all the new commits that could affect the infrastructure. 
How to use:
---------
- for all Github repositories:
```python
construct = FICGithub()
for repo in json.load(construct.load(None, "repositories.json")).get("Github"): …
```

Issue 438 - ( rewrited a part of PR #443 ) the logic that manage the commits from github repositories ( OOP )

---

modules/FIC_FileHandler.py
modules/FIC_Github.py

- This PR will implement the functionality to update the GIT .json files with the new commits , the last check date time and the last release version.
- The .json files have the following structure:
- last check and latest version
- the commits, starting with the newest at the top of .json
_get-release() - https://github.com/mozilla-releng/firefox-infra-changelog/commit/86704202c9a3397bcadf2e48690362b42c6933b4
-----
This commit changes the method to return a release version of our choosing by accepting an integer argument. If the argument is "1" it will return the latest version, "2" will return the second to latest version, and so on
_generate_first_element() - https://github.com/mozilla-releng/firefox-infra-changelog/commit/72e30c75764df11e7f1f8e1567397bd47b8c5ee3
-------
This method …

Issue 449 - update the Git json files 

---

modules/FIC_Github.py

This PR will fix the Issue #454 
====
In this case the method returns '0 == False' in case of the commit message not contain the keyword.
```python
228   if self.repo_type == "commit-keyword":
229       if self.keyword in self.commit_message:
230             return True
```
------
The method returns '0' if the repository is not build-puppet or if the commit message not contain the release_version.
```python 
232        elif self.repo_type == "tag":
233            if self.repo_name == "build-puppet":
234                return True
235
236            elif self.release_version in self.commit_message:
237                return True
```
-----
The following condition block returns '0' if the changed files are not affecting the infra.
```python
239        elif len(self.folders_to_check) > 0:
240 …
```

Issue 454 - fix the indentation issues in the _commit_filter() method

---

modules/FIC_Mercurial.py

This PR brings improvements to Mercurial part. 
Now, before running Mercurial part, the scrip will check if the expected final product (.json file) is present in data folder and acts accordingly. If the file is present, the script will just append the newest commits if not it will create the file with the last 100 changesets.

Add improvements to FIC_Mercurial.py

---

modules/FIC_Core.py
modules/FIC_Mercurial.py

This PR fixes issue #461 
To achieve the above mentioned flow the following changes were implemented:
* removed `self.hg_commits_list` as it wasn't used after initiated
* `list_of_dicts` was added to hold all the changesets which will later be written to json
* `_get_local_data` updates `list_of_dicts` with the old(local) chagnesets
* `changeset_dict` was added. This will contain the filtered data of one changeset at a time. The data is added here by `_add_changeset_data` and `_add_commit_data`. Once complete this dict is added to `list_of_dicts`
* after the iterations `list_of_dicts` will contain every changeset from oldest to newest
* `_populate_final_dict` updates `final_dict` and makes sure it is ready to be written to json
This way the json will contain the first element, changesets …

[Mercurial] Code Improvements

---

modules/FIC_Core.py
modules/FIC_DataVault.py
modules/FIC_FileHandler.py
modules/FIC_Github.py
plugins/FIC_Markdown.py

This PR fixes issue #414 
It handles the following:
* creation of individual MD files for every repo
* populates changelog.json
* creates changelog.md from changelog.json
`start_md_for_hg` and `start_md_for_git` and lastly `create_changelog_md`
The logic behind these is similar:
* they **_load_** the respective **_json file_** into an object
* a **_list_** will hold all the data to be written into the MD files
*  the **_structure of this list_** is: MD header + first table row  + each table row belonging to a commit
* each element of the **_completed list_** is **_appended_** to the proper MD file
For changelog.md a list of tupples was created. This helped with:
* sorting the repos into the order that we want them to be displayed
* figuring out if it is a git repo or a hg one
* iterating …

Markdown generation for changelog.md and individual repos

---

plugins/FIC_Markdown.py

This PR will fix the issue #466 
Added the following methods:  
- def _generate_repo_url(self, repository_type):
- to get the repository URL from  REPOSITORIES_FILE
- def no_data_for_md(self, repository_type, main_markdown=False, repo_markdown=False):
- to generate the message for MD in case of no changes:
-- repository_type: Github or Mercurial
-- main_markdown == True: returns the proper message for changelog.md
-- repo_markdown == True: returns the proper message for the individual GIT or HG repo  
Fixed the issues from lines: 102 and 129. 
if len(local_json_data) > 0: -> pass even if we have only one element (element 0 -> last_checked) 
if len(local_json_data) > 1: -> pass only if we have more than one element

Issue 466 - Handle MD tables when no data to be shown

---

plugins/FIC_Markdown.py

This pr fixes issue #469 
The md files are wiped clean before accepting all the new data that will be appended 
EDIT:
The last commits fixes issue #466 
The reason i added the changes here was to avoid merge conflicts
The code from the last commit deals with the situation when no data is to be shown & redirection is needed. 
See also: [https://github.com/mozilla-releng/firefox-infra-changelog/issues/466#issuecomment-497562471](https://github.com/mozilla-releng/firefox-infra-changelog/issues/466#issuecomment-497562471)

reset MD files before appending to them

---

modules/FIC_Core.py
modules/FIC_Logger.py

Issue #482 
If the Console Logging is activated by choosing the option number 5,
``` 5 . Activates logger output in console ```
the system will print the LOGGING data related to script on the console.

Issue 482 - Implemented the logging console

---

README.md

Updated Exit Code 4 usage docs: 07678b0
Removed exit code 3 from documentation, not used here: 4c3ea18
Removed exit code 9 (not implemented) and the last two table row cells (empty cells): 67f954d
Removed exit code 11 from documentation, not implemented in OOP: 5bf9ae6

Removed/Updated unsused exit codes.

---

.travis.yml

I've changed the .travis.yml file, by adding '-s' argument for skipping the main-menu when the script runs on Travis CI

Add argument '-s' to skip the menu when the script runs on Travis CI

---

requirements.txt

The package is used for GithubException object:
https://github.com/mozilla-releng/firefox-infra-changelog/blob/da6608adcf8c4f5b6a0886714a8c5f1a35e53d38/client.py#L5

Add 'pygithub' package to requirements.txt
